const LeadEngine={runId:null,running:false,phase:'idle',stats:null,items:[],filters:{},log:[]};
if(!NAV.some(n=>n[0]==='leads')) NAV.splice(2,0,['leads','users-round','Lead Engine']);
const _basePageHtml=pageHtml;
pageHtml=function(){return S.page==='leads'?leadEnginePage():_basePageHtml()};
const _baseBindApp=bindApp;
bindApp=function(){_baseBindApp();bindLeadEngine()};
function leLog(msg){LeadEngine.log.unshift({msg,at:new Date()});LeadEngine.log=LeadEngine.log.slice(0,12)}
function leStatus(){const s=LeadEngine.stats||{};return `<div class="le-status"><div><span>Run</span><b>${LeadEngine.runId?LeadEngine.runId.slice(0,8):'—'}</b></div><div><span>Products scanned</span><b>${s.products_seen||0}</b></div><div><span>Merchants found</span><b>${s.merchants_seen||0}</b></div><div><span>New merchants</span><b>${s.merchants_created||0}</b></div><div><span>Qualified results</span><b>${LeadEngine.items.length}</b></div><div><span>Status</span><b>${esc(s.status||LeadEngine.phase)}</b></div></div>`}
function leadEnginePage(){
 const rows=LeadEngine.items.slice(0,120).map(x=>{const cs=x.contacts||[];const email=cs.find(c=>c.channel==='email')?.value||'—',phone=cs.find(c=>c.channel==='phone')?.value||'—';return `<tr><td><b>${esc(x.name||'—')}</b><small>${esc(x.domain||'')}</small></td><td>${esc(x.category||'—')}</td><td>${esc(x.country||'—')}</td><td>${x.has_instagram?'Yes':'—'}</td><td>${esc(email)}</td><td>${esc(phone)}</td><td>${x.best_contact_score||0}</td><td>${x.score?.lumina_fit||'—'}</td><td><button class="row-action" data-merchant="${x.id}">Open</button></td></tr>`}).join('');
 const logs=LeadEngine.log.length?LeadEngine.log.map(x=>`<div class="le-log"><span>${fmtDate(x.at)}</span><b>${esc(x.msg)}</b></div>`).join(''):'<div class="le-muted">No run started yet.</div>';
 return pageIntro('discover','Find leads, enrich them, then rank what is worth contacting.','Search Shopify catalog demand, deduplicate merchants, inspect public business pages, collect contact routes and score each lead before outreach.',`<button class="secondary" id="leLoadRecent">${icon('history')} Recent runs</button><button class="primary" id="leRun" ${LeadEngine.running?'disabled':''}>${LeadEngine.running?'Running…':'Find leads'}</button>`)+`
 <section class="grid lead-engine-grid">
  <article class="card c4 le-builder"><div class="card-head"><div><h3>Lead brief</h3><small>Best-effort discovery from live Shopify catalog + public websites</small></div></div>
   <div class="field"><label>What businesses?</label><input id="leQuery" value="women's clothing brands" placeholder="e.g. swimwear brands"></div>
   <div class="split"><div class="field"><label>Country</label><select id="leCountry"><option value="US">United States</option><option value="GB">United Kingdom</option><option value="CA">Canada</option><option value="FR">France</option><option value="DE">Germany</option><option value="">Any</option></select></div><div class="field"><label>Target</label><select id="leLimit"><option>100</option><option selected>250</option><option>500</option><option>1000</option></select></div></div>
   <div class="field"><label>Category hint</label><input id="leCategory" value="Fashion" placeholder="Fashion, beauty, fitness…"></div>
   <div class="le-checks"><label><input type="checkbox" id="leEmail" checked> Email required</label><label><input type="checkbox" id="leInstagram"> Instagram required</label><label><input type="checkbox" id="lePhone"> Phone required</label></div>
   <div class="split"><div class="field"><label>Min contact score</label><input id="leContact" type="number" min="0" max="100" value="60"></div><div class="field"><label>Min Lumina Fit</label><input id="leFit" type="number" min="0" max="100" value="0"></div></div>
   <button class="primary le-big" id="leRun2" ${LeadEngine.running?'disabled':''}>${LeadEngine.running?'Working…':'Run discovery + enrichment'}</button>
   <p class="le-note">Current live sources: Shopify catalog + merchant public websites. Instagram follower counts and verified people databases need a separate provider connection.</p>
  </article>
  <article class="card c8"><div class="card-head"><div><h3>Run progress</h3><small>Discovery → dedupe → enrichment → contact ranking</small></div>${LeadEngine.runId?`<button class="secondary" id="leRefresh">Refresh results</button>`:''}</div>${leStatus()}<div class="le-pipeline"><span class="${LeadEngine.phase==='discovering'?'on':''}">1 Discover</span><i>→</i><span class="${LeadEngine.phase==='enriching'?'on':''}">2 Enrich</span><i>→</i><span class="${LeadEngine.phase==='filtering'||LeadEngine.phase==='done'?'on':''}">3 Rank</span><i>→</i><span class="${LeadEngine.phase==='done'?'on':''}">4 Ready</span></div><div class="le-console">${logs}</div></article>
  <article class="card full"><div class="card-head"><div><h3>Qualified lead list</h3><small>${LeadEngine.items.length} leads matching your current filters</small></div><button class="secondary" id="leExport" ${LeadEngine.items.length?'':'disabled'}>${icon('download')} Export CSV</button></div>${rows?`<div class="table-wrap"><table class="table le-table"><thead><tr><th>Business</th><th>Category</th><th>Country</th><th>Instagram</th><th>Email</th><th>Phone</th><th>Contact score</th><th>Lumina Fit</th><th></th></tr></thead><tbody>${rows}</tbody></table></div>`:empty('users-round','No qualified leads yet','Choose your filters and run the Lead Engine. Results will appear here as enrichment completes.')}</article>
 </section>`
}
function bindLeadEngine(){if(S.page!=='leads')return;document.getElementById('leRun')?.addEventListener('click',runLeadEngine);document.getElementById('leRun2')?.addEventListener('click',runLeadEngine);document.getElementById('leRefresh')?.addEventListener('click',refreshLeadResults);document.getElementById('leExport')?.addEventListener('click',exportLeadCsv);document.getElementById('leLoadRecent')?.addEventListener('click',loadRecentLeadRuns)}
async function leadCall(body){const {data,error}=await sb.functions.invoke('lead-engine',{body});if(error)throw new Error(error.message||'Lead Engine request failed');if(data?.error)throw new Error(data.error);return data}
function leadFilters(){return{require_email:document.getElementById('leEmail')?.checked||false,require_instagram:document.getElementById('leInstagram')?.checked||false,require_phone:document.getElementById('lePhone')?.checked||false,min_contact_score:Number(document.getElementById('leContact')?.value||0),min_fit:Number(document.getElementById('leFit')?.value||0)}}
async function runLeadEngine(){if(LeadEngine.running)return;const q=document.getElementById('leQuery')?.value.trim()||"women's clothing brands",country=document.getElementById('leCountry')?.value||null,category=document.getElementById('leCategory')?.value.trim()||null,limit=Number(document.getElementById('leLimit')?.value||250),filters=leadFilters();LeadEngine.running=true;LeadEngine.items=[];LeadEngine.log=[];LeadEngine.filters=filters;LeadEngine.phase='discovering';renderApp();try{leLog(`Searching ${q}${country?' in '+country:''}`);let r=await leadCall({action:'start',query:q,country,category,limit});LeadEngine.runId=r.run_id;LeadEngine.stats=r;renderApp();let safety=0;while(r.has_next_page&&r.status!=='completed'&&safety<20){leLog(`Discovery pass ${safety+2}: ${r.merchants_seen||0} merchants found`);r=await leadCall({action:'continue',run_id:LeadEngine.runId});LeadEngine.stats=r;renderApp();safety++}LeadEngine.phase='enriching';leLog(`Discovery finished with ${r.merchants_seen||0} merchants. Enriching public contact routes…`);renderApp();let remaining=1,batches=0;while(remaining>0&&batches<100){const e=await leadCall({action:'enrich',run_id:LeadEngine.runId,limit:8});remaining=Number(e.remaining||0);leLog(`Enriched ${e.processed||0} leads${e.phones_added?`, added ${e.phones_added} phone route(s)`:''}. ${remaining} remaining.`);batches++;if(e.processed===0)break;renderApp()}LeadEngine.phase='filtering';await refreshLeadResults(false);LeadEngine.phase='done';leLog(`${LeadEngine.items.length} qualified leads ready.`);await reload('merchants');await reload('contacts');await reload('scores');toast(`${LeadEngine.items.length} qualified leads ready.`, 'good')}catch(err){LeadEngine.phase='error';leLog(err.message||'Lead Engine failed');toast(err.message||'Lead Engine failed','bad')}finally{LeadEngine.running=false;renderApp()}}
async function refreshLeadResults(repaint=true){if(!LeadEngine.runId)return;const r=await leadCall({action:'results',run_id:LeadEngine.runId,filters:LeadEngine.filters||leadFilters()});LeadEngine.items=r.items||[];if(repaint)renderApp()}
async function loadRecentLeadRuns(){try{const r=await leadCall({action:'status'});const run=r.runs?.[0];if(!run)return toast('No previous lead runs yet.','bad');LeadEngine.runId=run.id;LeadEngine.stats=run;LeadEngine.phase=run.status==='completed'?'done':run.status;LeadEngine.filters=leadFilters();await refreshLeadResults(false);leLog(`Loaded recent run: ${run.query}`);renderApp()}catch(err){toast(err.message,'bad')}}
function exportLeadCsv(){if(!LeadEngine.items.length)return;const rows=LeadEngine.items.map(x=>{const c=x.contacts||[];return{name:x.name||'',domain:x.domain||'',website:x.website_url||'',country:x.country||'',category:x.category||'',platform:x.platform||'',instagram:x.instagram_url||c.find(y=>y.channel==='instagram')?.value||'',linkedin:x.linkedin_url||c.find(y=>y.channel==='linkedin')?.value||'',email:c.find(y=>y.channel==='email')?.value||'',phone:c.find(y=>y.channel==='phone')?.value||'',contact_score:x.best_contact_score||0,lumina_fit:x.score?.lumina_fit||'',recommended_offer:x.recommended_offer||'',recommended_channel:x.recommended_channel||''}});const csv=Papa.unparse(rows),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`lumina-view-leads-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href);toast('Lead CSV exported.','good')}